"""phase3 triage lifecycle, audit logs, pending commands

Revision ID: ca41c1ba0e02
Revises: 4823f807fcd2
Create Date: 2026-08-02 05:19:01.709685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca41c1ba0e02'
down_revision: Union[str, Sequence[str], None] = '4823f807fcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(bind, table: str, column: str) -> bool:
    from sqlalchemy import inspect

    return any(c["name"] == column for c in inspect(bind).get_columns(table))


def upgrade() -> None:
    """Upgrade schema.

    Adds the detection triage lifecycle columns and the Phase 3 audit +
    pending-command tables. All tables here are brand new; the only schema
    change to existing tables is adding the nullable triage columns to
    `detections`, which works both on a fresh DB and on Phase-2 legacy DBs.

    Column-existence checks use SQLAlchemy's cross-dialect inspector rather
    than SQLite-only `PRAGMA table_info`, so this migration also runs on
    PostgreSQL (the containerized backend).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('pending_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_commands_hostname'), 'pending_commands', ['hostname'], unique=False)
    op.create_index(op.f('ix_pending_commands_id'), 'pending_commands', ['id'], unique=False)
    bind = op.get_bind()
    if bind.dialect.has_table(bind, 'detections'):
        triage_columns: dict = {
            'triage_status': sa.Column('triage_status', sa.String(), nullable=True, server_default='new'),
            'triage_notes': sa.Column('triage_notes', sa.Text(), nullable=True),
            'triage_updated_at': sa.Column('triage_updated_at', sa.DateTime(timezone=True), nullable=True),
            'triage_updated_by': sa.Column('triage_updated_by', sa.String(), nullable=True),
        }
        for name, column in triage_columns.items():
            if not _has_column(bind, 'detections', name):
                op.add_column('detections', column)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'triage_updated_by')
    op.drop_column('detections', 'triage_updated_at')
    op.drop_column('detections', 'triage_notes')
    op.drop_column('detections', 'triage_status')
    op.drop_index(op.f('ix_pending_commands_id'), table_name='pending_commands')
    op.drop_index(op.f('ix_pending_commands_hostname'), table_name='pending_commands')
    op.drop_table('pending_commands')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
